apiVersion: v1
kind: Service
metadata:
  name: phpbb
  labels:
    app: phpbb
    provider: phpbb-server
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: phpbb
    provider: phpbb-server
