#helm:generate helmc tpl -d tpl/values.toml -o manifests/phpbb-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: phpbb
  labels:
    app: phpbb
    provider: phpbb-server
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: phpbb
    provider: phpbb-server
    version: 3.1.9-r0
  template:
    metadata:
      labels:
        app: phpbb
        provider: phpbb-server
        version: 3.1.9-r0
        heritage: bitnami
    spec:
      containers:
      - name: phpbb
        image: bitnami/phpbb:3.1.9-r0
        env:
        - name: MARIADB_HOST
          value: "mariadb"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        - name: PHPBB_USERNAME
          value: "user"
        - name: PHPBB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phpbb
              key: phpbb-password
        - name: PHPBB_EMAIL
          value: "user@example.com"
        - name: SMTP_HOST
          value: ""
        - name: SMTP_PORT
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phpbb
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: ""
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: phpbb-data
          mountPath: /bitnami/phpbb
        - name: apache-data
          mountPath: /bitnami/apache
        - name: php-data
          mountPath: /bitnami/php
      volumes:
      - name: phpbb-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
      - name: php-data
        emptyDir: {}
