{{- if .Values.metrics.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "zookeeper.fullname" . }}-exporter
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "zookeeper.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ template "zookeeper.name" . }}
    helm.sh/chart: {{ template "zookeeper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/component: {{ template "zookeeper.name" . }}-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "zookeeper.name" . }}
      release: "{{ .Release.Name }}"
      app.kubernetes.io/name: {{ template "zookeeper.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: {{ template "zookeeper.name" . }}-metrics
  template:
    metadata:
      annotations:
{{ toYaml .Values.metrics.podAnnotations | indent 8 }}
      labels:
        app: {{ template "zookeeper.name" . }}
        chart: {{ template "zookeeper.chart" . }}
        release: "{{ .Release.Name }}"
        app.kubernetes.io/name: {{ template "zookeeper.name" . }}
        helm.sh/chart: {{ template "zookeeper.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ template "zookeeper.name" . }}-metrics
    spec:
{{- include "zookeeper.imagePullSecrets" . | indent 6 }}
      containers:
      - image: {{ template "zookeeper.metrics.image" . }}
        name: zookeeper-exporter
        command:
          - /usr/local/bin/zookeeper-exporter
          - -zk-list
          {{- $replicaCount := int .Values.replicaCount }}
          {{- $followerPort := int .Values.service.followerPort }}
          {{- $electionPort := int .Values.service.electionPort }}
          {{- $servicePort := int .Values.service.port }}
          {{- $releaseNamespace := .Release.Namespace }}
          {{- $zookeeperFullname := include "zookeeper.fullname" . }}
          {{- $zookeeperHeadlessServiceName := printf "%s-%s" $zookeeperFullname "headless" | trunc 63  }}
          - {{range $i, $e := until $replicaCount }}{{ $zookeeperFullname }}-{{ $e }}.{{ $zookeeperHeadlessServiceName }}.{{ $releaseNamespace }}.svc.cluster.local:{{ $servicePort }}{{- if (lt $e ( sub $replicaCount 1)) -}},{{- end -}}{{ end }}
        ports:
          - name: metrics
            containerPort: 8080
        resources:
{{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
