#helm:generate helmc tpl -d tpl/values.toml -o manifests/ghost-svc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
    provider: ghost-server
    heritage: bitnami
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .ghostHostIP }}
  ports:
  - name: http
    port: {{ .ghostPort }}
    targetPort: http
  selector:
    app: ghost
    provider: ghost-server
