wordpressUsername = "user"
wordpressPassword = "bitnami"
wordpressEmail = "user@example.com"
wordpressFirstName = "FirstName"
wordpressLastName = "LastName"
wordpressBlogName = "User's Blog!"
smtpHost = ""
smtpPort = ""
smtpUser = ""
smtpPassword = ""
smtpUsername = ""
smtpProtocol = ""
