#helm:generate helmc tpl -d tpl/values.toml -o manifests/wordpress-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress
  labels:
    app: wordpress
    provider: wordpress-server
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: wordpress
    provider: wordpress-server
    version: 4.5.3-r0
  template:
    metadata:
      labels:
        app: wordpress
        provider: wordpress-server
        version: 4.5.3-r0
        heritage: bitnami
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress:4.5.3-r0
        env:
        - name: MARIADB_HOST
          value: "mariadb"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        - name: WORDPRESS_USERNAME
          value: {{ .wordpressUsername | quote }}
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: wordpress-password
        - name: WORDPRESS_EMAIL
          value: {{ .wordpressEmail | quote }}
        - name: WORDPRESS_FIRSTNAME
          value: {{ .wordpressFirstName | quote }}
        - name: WORDPRESS_LASTNAME
          value: {{ .wordpressLastName | quote }}
        - name: WORDPRESS_BLOGNAME
          value: {{ .wordpressBlogName | quote }}
        - name: SMTP_HOST
          value: {{ .smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ .smtpPort | quote }}
        - name: SMTP_USER
          value: {{ .smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: smtp-password
        - name: SMTP_USERNAME
          value: {{ .smtpUsername | quote }}
        - name: SMTP_PROTOCOL
          value: {{ .smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: wordpress-data
          mountPath: /bitnami/wordpress
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: wordpress-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
