apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "mediawiki" | trunc 24 }}
  labels:
    app: mediawiki
    provider: mediawiki-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: mediawiki
    provider: mediawiki-server
    release: {{ .Release.Name }}
