apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "mediawiki" | trunc 24 }}
  labels:
    app: mediawiki
    provider: mediawiki-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: mediawiki
    provider: mediawiki-server
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        app: mediawiki
        provider: mediawiki-server
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: mediawiki
        image: bitnami/mediawiki:{{ .Values.imageTag }}
        env:
        - name: MARIADB_HOST
          value: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 | quote }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
              key: mariadb-root-password
        - name: MEDIAWIKI_USERNAME
          value: {{ .Values.mediawikiUser | quote }}
        - name: MEDIAWIKI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mediawiki" | trunc 24 }}
              key: mediawiki-password
        - name: MEDIAWIKI_EMAIL
          value: {{ .Values.mediawikiEmail | quote }}
        - name: MEDIAWIKI_WIKI_NAME
          value: {{ .Values.mediawikiName | quote }}
        - name: SMTP_HOST_ID
          value: {{ .Values.smtpHostID | quote }}
        - name: SMTP_HOST
          value: {{ .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ .Values.smtpUser | quote }}
        - name: SMTP_Password
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mediawiki" | trunc 24 }}
              key: smtp-password
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: mediawiki-data
          mountPath: /bitnami/mediawiki
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: mediawiki-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
