apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "master.fullname" . }}
  labels:
    app: {{ template "master.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  my.cnf: |-
{{- if .Values.master.config }}
{{ .Values.master.config | indent 4 }}
{{- end -}}
