apiVersion: v1
kind: Service
metadata:
  name: {{ template "master.fullname" . }}
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "{{ template "name" . }}"
    component: "master"
    release: "{{ .Release.Name }}"
