{{- if .Values.master.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "master.fullname" . }}
  labels:
    app: {{ template "master.fullname" . }}
    chart: {{ template "mariadb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  my.cnf: |-
{{ .Values.master.config | indent 4 }}
{{- end -}}
