apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mariadbRootPassword }}
  mariadb-root-password: {{ .Values.mariadbRootPassword | b64enc | quote }}
  {{ else }}
  mariadb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mariadbUser }}
  {{ if .Values.mariadbPassword }}
  mariadb-password: {{ .Values.mariadbPassword | b64enc | quote }}
  {{ else }}
  mariadb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ end }}
  {{ if .Values.mariadbReplicationPassword }}
  mariadb-replication-password: {{ .Values.mariadbReplicationPassword | b64enc | quote }}
  {{ else }}
  mariadb-replication-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
