{{- if and .Values.replication.enabled .Values.slave.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "slave.fullname" . }}
  labels:
    app: {{ template "name" . }}
    component: "slave"
    chart: {{ template "mariadb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  my.cnf: |-
{{ .Values.slave.config | indent 4 }}
{{- end -}}
