apiVersion: v1
kind: Service
metadata:
  name: {{ template "slave.fullname" . }}
  labels:
    app: {{ template "slave.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: {{ template "slave.fullname" . }}
