apiVersion: v1
kind: Service
metadata:
  name: {{ template "slave.fullname" . }}
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
    targetPort: mysql
  selector:
    app: "{{ template "name" . }}"
    component: "slave"
    release: "{{ .Release.Name }}"
