apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "slave.fullname" . }}
  labels:
    app: {{ template "slave.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ default "1" .Values.replicasCount }}
  template:
    metadata:
      labels:
        app: {{ template "slave.fullname" . }}
    spec:
      containers:
      - name: {{ template "slave.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-root-password
        - name: MARIADB_USER
          value: {{ default "" .Values.mariadbUser | quote }}
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: {{ default "" .Values.mariadbDatabase | quote }}
        - name: MARIADB_REPLICATION_MODE
          value: "slave"
        - name: MARIADB_MASTER_HOST
          value: {{ template "master.fullname" . }}
        - name: MARIADB_MASTER_PORT
          value: "3306"
        - name: MARIADB_MASTER_USER
          value: "root"
        - name: MARIADB_MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-root-password
        - name: MARIADB_REPLICATION_USER
          value: {{ default "" .Values.mariadbReplicationUser | quote }}
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-replication-password
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: mariadb-slave-data
          mountPath: /bitnami/mariadb
      volumes:
      - name: mariadb-slave-data
        emptyDir: {}
