{{- if and (.Values.slave.persistence.enabled) (.Values.replication.enabled) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "slave.fullname" . }}-data
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.slave.persistence.annotations }}
  annotations:
{{ toYaml .Values.slave.persistence.annotations | indent 2 }}
{{- end }}
spec:
  accessModes:
{{ toYaml .Values.slave.persistence.accessModes | indent 2 }}
  resources:
    requests:
      storage: "{{ .Values.slave.persistence.size }}"
{{- if .Values.slave.persistence.storageClass }}
{{- if (eq "-" .Values.slave.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.slave.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
