apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "slave.fullname" . }}
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "slave"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ default "1" .Values.numSlaves }}
  template:
    metadata:
      labels:
        app: "{{ template "name" . }}"
        component: "slave"
        release: "{{ .Release.Name }}"
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      {{- if eq .Values.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "name" . }}"
                  release: "{{ .Release.Name }}"
      {{- else if eq .Values.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "name" . }}"
                  release: "{{ .Release.Name }}"
      {{- end }}
      containers:
      - name: "mariadb"
        image: "{{ .Values.image }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-root-password
        {{- if .Values.mariadbUser }}
        - name: MARIADB_USER
          value: "{{ .Values.mariadbUser }}"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-password
        {{- end }}
        - name: MARIADB_DATABASE
          value: "{{ .Values.mariadbDatabase }}"
        - name: MARIADB_REPLICATION_MODE
          value: "slave"
        - name: MARIADB_MASTER_HOST
          value: {{ template "master.fullname" . }}
        - name: MARIADB_MASTER_PORT
          value: "3306"
        - name: MARIADB_MASTER_USER
          value: "root"
        - name: MARIADB_MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-root-password
        - name: MARIADB_REPLICATION_USER
          value: "{{ .Values.mariadbReplicationUser }}"
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-replication-password
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 120
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 15
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: data
          mountPath: /bitnami
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "slave.fullname" . }}
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "slave"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ template "slave.fullname" . }}
  targetCPUUtilizationPercentage: 50
