{{- if (not .Values.dbUser.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cassandra.fullname" . }}
  labels:
    app: "{{ template "cassandra.name" . }}"
    chart: {{ template "cassandra.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.dbUser.password }}
  cassandra-password: "{{ .Values.dbUser.password | b64enc }}"
  {{- else if (not .Values.dbUser.forcePassword) }}
  cassandra-password: "{{ randAlphaNum 10 | b64enc }}"
  {{ else }}
  cassandra-password: {{ required "A Cassandra Password is required!" .Values.dbUser.password }}
  {{- end }}
{{- end }}
