apiVersion: v1
kind: Service
metadata:
  name: {{ template "cassandra.fullname" . }}-headless
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ template "cassandra.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: intra
    port: 7000
    targetPort: intra
  - name: tls
    port: 7001
    targetPort: tls
  - name: jmx
    port: 7199
    targetPort: jmx
  - name: cql
    port: {{ default 9042 .Values.service.cqlPort }}
    targetPort: cql
  - name: thrift
    port: {{ default 9160 .Values.service.thriftPort }}
    targetPort: thrift
  selector:
    app: {{ template "cassandra.name" . }}
    release: {{ .Release.Name }}
