apiVersion: v1
kind: Service
metadata:
  name: {{ template "cassandra.fullname" . }}
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ template "cassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.service.nodePort }}
  nodePort: {{ .Values.service.nodePort }}
{{- end }}
{{ if eq .Values.service.type "LoadBalancer" -}} {{ if .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end -}} {{- end }}
  type: {{ .Values.service.type }}
  ports:
  - name: cql
    port: {{ default 9042 .Values.service.cqlPort }}
    targetPort: cql
  - name: thrift
    port: {{ default 9160 .Values.service.thriftPort }}
    targetPort: thrift
  selector:
    app: {{ template "cassandra.name" . }}
    release: {{ .Release.Name }}
