#helm:generate helm tpl -d tpl/values.toml -o manifests/redmine-controller.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine
  labels:
    app: redmine
    provider: redmine-server
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: redmine
    provider: redmine-server
    version: 3.2.1-0
  template:
    metadata:
      labels:
        app: redmine
        provider: redmine-server
        version: 3.2.1-0
        heritage: bitnami
    spec:
      containers:
      - name: redmine
        image: bitnami/redmine:3.2.1-0
        env:
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          value: {{.mariadbPassword}}
        - name: REDMINE_USERNAME
          value: {{.redmineUser}}
        - name: REDMINE_PASSWORD
          value: {{.redminePassword}}
        - name: REDMINE_EMAIL
          value: {{.redmineEmail}}
        - name: REDMINE_LANG
          value: {{.redmineLanguage}}
        ports:
        - name: redmine-http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/redmine
      volumes:
      - name: data
        emptyDir: {}
