#helm:generate helm tpl -d tpl/values.toml -o manifests/redmine-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine
  labels:
    app: redmine
    provider: redmine-server
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: redmine
    provider: redmine-server
    version: 3.2.1-1
  template:
    metadata:
      labels:
        app: redmine
        provider: redmine-server
        version: 3.2.1-1
        heritage: bitnami
    spec:
      containers:
      - name: redmine
        image: bitnami/redmine:3.2.1-1
        env:
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          value: "{{.mariadbPassword}}"
        - name: REDMINE_USERNAME
          value: "{{.redmineUser}}"
        - name: REDMINE_PASSWORD
          value: "{{.redminePassword}}"
        - name: REDMINE_EMAIL
          value: "{{.redmineEmail}}"
        - name: REDMINE_LANG
          value: "{{.redmineLanguage}}"
        - name: SMTP_HOST
          value: "{{.smtpHost}}"
        - name: SMTP_PORT
          value: "{{.smtpPort}}"
        - name: SMTP_USER
          value: "{{.smtpUser}}"
        - name: SMTP_PASSWORD
          value: "{{.smtpPassword}}"
        - name: SMTP_TLS
          value: "{{.smtpTls}}"
        ports:
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/redmine
      volumes:
      - name: data
        emptyDir: {}
