#helm:generate helmc tpl -d tpl/values.toml -o manifests/tomcat-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: tomcat
  labels:
    provider: tomcat
    heritage: bitnami
type: Opaque
data:
  tomcat-password: ""
