apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    provider: tomcat
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    provider: tomcat
