apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "mongodb" | trunc 24 }}
  labels:
    provider: mongodb
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    provider: mongodb
