apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    provider: memcached
    heritage: bitnami
spec:
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
  selector:
    provider: memcached
