#helm:generate helmc tpl -d tpl/values.toml -o manifests/memcached-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: memcached
  labels:
    provider: memcached
    heritage: bitnami
type: Opaque
data:
  memcached-password: ""
