apiVersion: v1
kind: Service
metadata:
  name: wildfly
  labels:
    provider: wildfly
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: mgmt
    port: 9990
    targetPort: mgmt
  selector:
    provider: wildfly
