apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "master" | trunc 24 }}
  labels:
    provider: mariadb
    mode: master
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    provider: mariadb
    mode: master
    release: {{ .Release.Name }}
