name: tomcat
version: 0.3.5
description: Chart for Apache Tomcat
keywords:
- tomcat
- java
- http
- web
- application server
- jsp
home: http://tomcat.apache.org
sources:
- https://github.com/bitnami/bitnami-docker-tomcat
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
