#helm:generate helmc tpl -d tpl/values.toml -o manifests/testlink-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: testlink
  labels:
    app: testlink
    provider: testlink-server
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: testlink
    provider: testlink-server
    version: 1.9.14-r0
  template:
    metadata:
      labels:
        app: testlink
        provider: testlink-server
        version: 1.9.14-r0
        heritage: bitnami
    spec:
      containers:
      - name: testlink
        image: bitnami/testlink:1.9.14-r0
        env:
        - name: MARIADB_HOST
          value: "mariadb"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        - name: TESTLINK_USERNAME
          value: {{ .testlinkUsername | quote }}
        - name: TESTLINK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: testlink
              key: testlink-password
        - name: TESTLINK_EMAIL
          value: {{ .testlinkEmail | quote }}
        - name: TESTLINK_LANGUAGE
          value: {{ .testlinkLanguage | quote }}
        - name: TESTLINK_SMTP_ENABLE
          value: {{ .testlinkSmtpEnable | quote }}
        - name: TESTINK_SMTP_CONNECTION_MODE
          value: {{ .testlinkSmtpConnectionMode | quote }}
        - name: SMTP_HOST
          value: {{ .smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ .smtpPort | quote }}
        - name: SMTP_USER
          value: {{ .smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: testlink
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ .smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: testlink-data
          mountPath: /bitnami/testlink
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: testlink-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
