apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}-aggregator-cm
  labels: {{ include "fluentd.labels" . | nindent 4 }}
data:
  aggregator.conf: |
    <match fluent.**>
      @type null
    </match>

    # TCP input
    <source>
      @type forward
      bind 0.0.0.0
      port {{ .Values.aggregator.port }}
    </source>

    # HTTP input
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    <match fluentd.healthcheck>
      @type stdout
    </match>

    <match **>
      @type stdout
    </match>
