apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    provider: redis
    heritage: bitnami
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    provider: redis
