apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: MARIADB_HOST
          value: {{ template "mariadb.fullname" . }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.fullname" . }}
              key: mariadb-root-password
        - name: SUGARCRM_USERNAME
          value: {{ default "" .Values.suitecrmUsername | quote }}
        - name: SUGARCRM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: suitecrm-password
        - name: SUGARCRM_EMAIL
          value: {{ default "" .Values.suitecrmEmail | quote }}
        - name: SUGARCRM_LASTNAME
          value: {{ default "" .Values.suitecrmLastname | quote }}
        - name: SUGARCRM_HOST
          value: {{ default "" .Values.suitecrmHost | quote }}
        - name: SUGARCRM_SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SUGARCRM_SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SUGARCRM_SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SUGARCRM_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: smtp-password
        - name: SUGARCRM_SMTP_PROTOCOL
          value: {{ default "" .Values.smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: suitecrm-data
          mountPath: /bitnami/suitecrm
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: suitecrm-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-suitecrm
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: apache-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-apache
      {{- else }}
        emptyDir: {}
      {{- end }}
