apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "redis" | trunc 24 }}
  labels:
    provider: redis
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    provider: redis
    release: {{ .Release.Name }}
