apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "phpbb" | trunc 24 }}
  labels:
    app: phpbb
    provider: phpbb-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: phpbb
    provider: phpbb-server
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        app: phpbb
        provider: phpbb-server
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: phpbb
        image: bitnami/phpbb:{{ .Values.imageTag }}
        env:
        - name: MARIADB_HOST
          value: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 | quote }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
              key: mariadb-root-password
        - name: PHPBB_USERNAME
          value: {{ default "" .Values.phpbbUser | quote }}
        - name: PHPBB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "phpbb" | trunc 24 }}
              key: phpbb-password
        - name: PHPBB_EMAIL
          value: {{ default "" .Values.phpbbEmail | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "phpbb" | trunc 24 }}
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ default "" .Values.smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: phpbb-data
          mountPath: /bitnami/phpbb
        - name: apache-data
          mountPath: /bitnami/apache
        - name: php-data
          mountPath: /bitnami/php
      volumes:
      - name: phpbb-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
      - name: php-data
        emptyDir: {}
