name: redmine
home: https://github.com/bitnami/charts/tree/master/redmine
version: 0.1.0
description: A flexible project management web application.
maintainers:
- Bitnami <containers@bitnami.com>
details: |-
  Redmine is a flexible project management web application written using Ruby on Rails framework.
