#helm:generate helmc tpl -d tpl/values.toml -o manifests/mariadb-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    provider: mariadb
    heritage: bitnami
type: Opaque
data:
  mariadb-root-password: ""
  mariadb-password: ""
