apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    provider: wordpress-server
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: wordpress
    provider: wordpress-server
