#helm:generate helmc tpl -d tpl/values.toml -o manifests/rabbitmq-svc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    provider: rabbitmq
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: rabbitmq
    port: {{ .rabbitmqNodeport }}
    targetPort: rabbitmq
  - name: rabbitmq-mgmt
    port: {{ .rabbitmqManagerport }}
    targetPort: rabbitmq-mgmt
  selector:
    provider: rabbitmq
