#helm:generate helmc tpl -d tpl/values.toml -o manifests/rabbitmq-svc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    provider: rabbitmq
    heritage: bitnami
spec:
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: ampq
    port: {{ .rabbitmqNodeport }}
    targetPort: ampq
  - name: dist
    port: {{ add 20000 .rabbitmqNodeport }}
    targetPort: dist
  - name: stats
    port: {{ .rabbitmqManagerport }}
    targetPort: stats
  selector:
    provider: rabbitmq
