rabbitmqUsername = "user"
rabbitmqPassword = "bitnami"
rabbitmqErlangcookie = ""
rabbitmqNodeport = "5672"
rabbitmqNodetype = "stats"
rabbitmqNodename = "rabbit"
rabbitmqClusternodename = ""
rabbitmqVhost = "/"
rabbitmqManagerbindip = "0.0.0.0"
rabbitmqManagerport = "15672"
