rabbitmqUsername = "user"
rabbitmqPassword = "bitnami"
rabbitmqErlangcookie = ""
rabbitmqNodeport = "5672"
rabbitmqNodetype = "stats"
rabbitmqNodename = "rabbit"
rabbitmqClusternodename = ""
rabbitmqVhost = "/"
rabbitmqManagerport = "15672"
