#helm:generate helmc tpl -d tpl/values.toml -o manifests/phpbb-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: phpbb
  labels:
    provider: phpbb
    heritage: bitnami
type: Opaque
data:
  phpbb-password: {{ .phpbbPassword | b64enc | quote }}
  smtp-password: {{ .smtpPassword | b64enc | quote }}
