apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "wildfly" | trunc 24 }}
  labels:
    provider: wildfly
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: mgmt
    port: 9990
    targetPort: mgmt
  selector:
    provider: wildfly
    release: {{ .Release.Name }}
