apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "wildfly" | trunc 24 }}
  labels:
    provider: wildfly
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: wildfly
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        provider: wildfly
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: wildfly
        image: bitnami/wildfly:{{ .Values.imageTag }}
        env:
        - name: WILDFLY_USER
          value: {{ default "" .Values.wildflyUser | quote }}
        - name: WILDFLY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "wildfly" | trunc 24 }}
              key: wildfly-password
        ports:
        - name: http
          containerPort: 8080
        - name: mgmt
          containerPort: 9990
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/wildfly
      volumes:
      - name: data
        emptyDir: {}
