#helm:generate helmc tpl -d tpl/values.toml -o manifests/drupal-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: drupal
  labels:
    provider: drupal
    heritage: bitnami
type: Opaque
data:
  mariadb-root-password: ""
  drupal-password: "Yml0bmFtaQ=="
