{{- if .Values.externaldb.broker.serviceInstanceName }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ template "node.fullname" . }}-mongodb-binding
  labels:
    app: {{ template "node.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  instanceRef:
    name: {{ .Values.externaldb.broker.serviceInstanceName }}
{{- if .Values.externaldb.broker.serviceInstanceName }}
  secretName: {{ .Values.externaldb.secretName }}
{{ else }}
  secretName: {{ template "node.fullname" . }}-mongodb-secret
{{- end }}
{{- end }}
