apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    app: odoo
    provider: odoo-server
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: odoo
    provider: odoo-server
