apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "drupal" | trunc 24 }}
  labels:
    app: drupal
    provider: drupal-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: drupal
    provider: drupal-server
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        app: drupal
        provider: drupal-server
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: drupal
        image: bitnami/drupal:{{ .Values.imageTag }}
        env:
        - name: MARIADB_HOST
          value: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 | quote }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
              key: mariadb-root-password
        - name: DRUPAL_USERNAME
          value: {{ .Values.drupalUser | quote }}
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "drupal" | trunc 24 }}
              key: drupal-password
        - name: DRUPAL_EMAIL
          value: {{ .Values.drupalEmail | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: drupal-data
          mountPath: /bitnami/drupal
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: drupal-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
