name: sugarcrm
version: 0.0.1
description: Sugar offers the most innovative, flexible and affordable CRM in the market and delivers the best all-around value of any CRM.
keywords:
- sugarcrm
- CRM
- php
- mariadb
home: http://www.sugarcrm.org/
sources:
- https://github.com/bitnami/bitnami-docker-sugarcrm
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
icon: http://d2owqhhe2x3j50.cloudfront.net/D7-images/header.png
