apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  elasticsearch_custom.yml: |-

    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}

    cloud:
      kubernetes:
        service: ${SERVICE}
        namespace: ${KUBERNETES_NAMESPACE}

    discovery:
      zen:
        hosts_provider: kubernetes

    plugin:
      mandatory: discovery-kubernetes

{{- if .Values.cluster.config }}
{{ toYaml .Values.cluster.config | indent 4 }}
{{- end }}
