apiVersion: v1
kind: Service
metadata:
  name: {{ template "coordinating.fullname" . | quote }}
  labels:
    app: {{ template "elasticsearch.name" . | quote }}
    chart: {{ template "elasticsearch.chart" . | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: "coordinating-only"
spec:
  type: {{ .Values.coordinating.service.type | quote }}
  ports:
  - name: http
    port: {{ .Values.coordinating.service.port }}
    targetPort: http
  selector:
    app: {{ template "elasticsearch.name" . | quote }}
    release: {{ .Release.Name | quote }} 
    role: "coordinating-only"
