{{- if .Values.ingest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ingest.fullname" . | quote }}
  labels:
    app: {{ template "elasticsearch.name" . | quote }}
    chart: {{ template "elasticsearch.chart" . | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: "ingest"
spec:
  ports:
  - name: transport
    port: 9300
    targetPort: transport
  selector:
    app: {{ template "elasticsearch.name" . | quote }}
    release: {{ .Release.Name | quote }}
    role: "ingest"
{{- end }}
