apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - name: "http"
    port: {{ .Values.elasticsearchPortNumber }}
    targetPort: "http"
  - name: "transport"
    port: {{ .Values.elasticsearchNodePortNumber }}
    targetPort: "transport"
  selector:
    app: "{{ template "name" . }}"
    release: "{{ .Release.Name }}"
