apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-transport"
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: "transport"
    port: 9300
    targetPort: "transport"
  selector:
    app: "{{ template "name" . }}"
    release: "{{ .Release.Name }}"
    component: "master"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-http"
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - name: "http"
    port: {{ .Values.service.port.http }}
    targetPort: "http"
  selector:
    app: "{{ template "name" . }}"
    release: "{{ .Release.Name }}"
    component: "master"
