apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  labels:
    provider: mariadb
    mode: master
    heritage: bitnami
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    provider: mariadb
    mode: master
