#helm:generate helmc tpl -d tpl/values.toml -o manifests/phabricator-svc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Service
metadata:
  name: phabricator
  labels:
    app: phabricator
    provider: phabricator-server
    heritage: bitnami
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .phabricatorHostIP }}
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: phabricator
    provider: phabricator-server
