phabricatorUsername = "user"
phabricatorPassword = "bitnami1"
phabricatorEmail = "user@example.com"
phabricatorFirstName = "First Name"
phabricatorLastName = "Last Name"
phabricatorHost = ""
phabricatorHostIP = ""
smtpUser = ""
smtpPassword = ""
smtpHost = ""
smtpPort = ""
smtpProtocol = ""
