#helm:generate helmc tpl -d tpl/values.toml -o manifests/joomla-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: joomla
  labels:
    app: joomla
    provider: joomla-server
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: joomla
    provider: joomla-server
    version: 3.6.0-r0
  template:
    metadata:
      labels:
        app: joomla
        provider: joomla-server
        version: 3.6.0-r0
        heritage: bitnami
    spec:
      containers:
      - name: joomla
        image: bitnami/joomla:3.6.0-r0
        env:
        - name: MARIADB_HOST
          value: "mariadb"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        - name: JOOMLA_USERNAME
          value: "user"
        - name: JOOMLA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: joomla
              key: joomla-password
        - name: JOOMLA_EMAIL
          value: "user@example.com"
        - name: SMTP_HOST
          value: ""
        - name: SMTP_PORT
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: joomla
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: ""
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: joomla-data
          mountPath: /bitnami/joomla
        - name: apache-data
          mountPath: /bitnami/apache
        - name: php-data
          mountPath: /bitnami/php
      volumes:
      - name: joomla-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
      - name: php-data
        emptyDir: {}
