apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "memcached" | trunc 24 }}
  labels:
    provider: memcached
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
  selector:
    provider: memcached
    release: {{ .Release.Name }}
