#helm:generate helmc tpl -d tpl/values.toml -o manifests/mediawiki-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: mediawiki
  labels:
    provider: mediawiki
    heritage: bitnami
type: Opaque
data:
  mediawiki-password: {{ .mediawikiPassword | b64enc | quote }}
  smtp-password: {{ .smtpPassword | b64enc | quote }}
