mariadbRootPassword = ""
mediawikiUser = "user"
mediawikiPassword = "bitnami1"
mediawikiEmail = "user@example.com"
mediawikiName = "Bitnami MediaWiki"
smtpHost = ""
smtpHostID = ""
smtpPort = ""
smtpUser = ""
smtpPassword = ""
