#helm:generate helmc tpl -d tpl/values.toml -o manifests/mariadb-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
  labels:
    provider: mariadb
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: mariadb
    version: 10.1.14-r1
  template:
    metadata:
      labels:
        provider: mariadb
        version: 10.1.14-r1
        heritage: bitnami
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:10.1.14-r1
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        - name: MARIADB_USER
          value: {{ .mariadbUser | quote }}
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: {{ .mariadbDatabase | quote }}
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
      volumes:
      - name: data
        emptyDir: {}
