#helm:generate helm tpl -d tpl/values.toml -o manifests/mariadb-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
  labels:
    provider: mariadb
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: mariadb
    version: 5.5.48-0-r01
  template:
    metadata:
      labels:
        provider: mariadb
        version: 5.5.48-0-r01
        heritage: bitnami
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:5.5.48-0-r01
        env:
        - name: MARIADB_PASSWORD
          value: {{.mariadbPassword}}
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb/data
        - name: conf
          mountPath: /bitnami/mariadb/conf
        - name: logs
          mountPath: /bitnami/mariadb/logs
      volumes:
      - name: data
        emptyDir: {}
      - name: conf
        emptyDir: {}
      - name: logs
        emptyDir: {}
