apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "odoo" | trunc 24 }}
  labels:
    app: odoo
    provider: odoo-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: odoo
    provider: odoo-server
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        app: odoo
        provider: odoo-server
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: odoo
        image: bitnami/odoo:{{ .Values.imageTag }}
        env:
        - name: POSTGRESQL_HOST
          value: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 24 | quote }}
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 24 }}
              key: postgres-password
        - name: ODOO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "odoo" | trunc 24 }}
              key: odoo-password
        - name: ODOO_EMAIL
          value: {{ default "" .Values.odooEmail | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "odoo" | trunc 24 }}
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ default "" .Values.smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 8069
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/odoo
      volumes:
      - name: data
        emptyDir: {}
