apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  odoo-password: {{ default "" .Values.odooPassword | b64enc | quote }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
