#helm:generate helmc tpl -d tpl/values.toml -o manifests/mongodb-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    provider: mongodb
    heritage: bitnami
type: Opaque
data:
  mongodb-root-password: ""
  mongodb-password: ""
