#helm:generate helmc tpl -d tpl/values.toml -o manifests/mongodb-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
  labels:
    provider: mongodb
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: mongodb
    version: 3.2.7-r0
  template:
    metadata:
      labels:
        provider: mongodb
        version: 3.2.7-r0
        heritage: bitnami
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:3.2.7-r0
        env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        - name: MONGODB_USER
          value: ""
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-password
        - name: MONGODB_DATABASE
          value: ""
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongo
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
      volumes:
      - name: data
        emptyDir: {}
