name: orangehrm
version: 0.3.2
description: OrangeHRM is a free HR management system that offers a wealth of modules to suit the needs of your business.
keywords:
- orangehrm
- http
- https
- web
- application
- php
- human resources
home: https://www.orangehrm.com
sources:
- https://github.com/bitnami/bitnami-docker-orangehrm
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
