## Bitnami Phabricator image version
## ref: https://hub.docker.com/r/bitnami/orangehrm/tags/
##
imageTag: 3.3.3-r1

## Specify a imagePullPolicy
## Defaults to 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## User of the application
## ref: https://github.com/bitnami/bitnami-docker-orangehrm#configuration
##
orangehrmUsername: admin

## Application password
## ref: https://github.com/bitnami/bitnami-docker-orangehrm#configuration
##
orangehrmPassword: bitnami

## SMTP mail delivery configuration
## ref: https://github.com/bitnami/bitnami-docker-redmine/#smtp-configuration
##
# smtpHost:
# smtpPort:
# smtpUser:
# smtpPassword:
# smtpProtocol:

## MariaDB chart configuration
##
# mariadb:
  ## MariaDB admin password
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  # mariadbRootPassword:
