apiVersion: v1
kind: ReplicationController
metadata:
  name: apache
  labels:
    provider: apache
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: apache
    version: 2.4.18-0
  template:
    metadata:
      labels:
        provider: apache
        version: 2.4.18-0
        heritage: bitnami
    spec:
      containers:
      - name: apache
        image: bitnami/apache:2.4.18-0
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: htdocs
          mountPath: /app
        - name: conf
          mountPath: /bitnami/apache/conf
      volumes:
      - name: htdocs
        emptyDir: {}
      - name: conf
        emptyDir: {}
