apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    provider: apache
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: apache-http
    port: 80
  - name: https
    targetPort: apache-https
    port: 443
  selector:
    provider: apache
