apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
  labels:
    provider: mariadb
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: mariadb
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        provider: mariadb
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:{{ .Values.imageTag }}
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
              key: mariadb-root-password
        - name: MARIADB_USER
          value: {{ .Values.mariadbUser | quote }}
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: {{ .Values.mariadbDatabase | quote }}
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
      volumes:
      - name: data
        emptyDir: {}
