#helm:generate helmc tpl -d tpl/values.toml -o manifests/odoo-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: odoo
  labels:
    provider: odoo
    heritage: bitnami
type: Opaque
data:
  odoo-password: {{ .odooPassword | b64enc | quote }}
  smtp-password: {{ .smtpPassword | b64enc | quote }}
