apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "testlink" | trunc 24 }}
  labels:
    app: testlink
    provider: testlink-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: testlink
    provider: testlink-server
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        app: testlink
        provider: testlink-server
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: testlink
        image: bitnami/testlink:{{ .Values.imageTag }}
        env:
        - name: MARIADB_HOST
          value: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 | quote }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
              key: mariadb-root-password
        - name: TESTLINK_USERNAME
          value: {{ default "" .Values.testlinkUsername | quote }}
        - name: TESTLINK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "testlink" | trunc 24 }}
              key: testlink-password
        - name: TESTLINK_EMAIL
          value: {{ default "" .Values.testlinkEmail | quote }}
        - name: TESTLINK_LANGUAGE
          value: {{ default "" .Values.testlinkLanguage | quote }}
        - name: TESTLINK_SMTP_ENABLE
          value: {{ default "" .Values.testlinkSmtpEnable | quote }}
        - name: TESTINK_SMTP_CONNECTION_MODE
          value: {{ default "" .Values.testlinkSmtpConnectionMode | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "testlink" | trunc 24 }}
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ default "" .Values.smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: testlink-data
          mountPath: /bitnami/testlink
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: testlink-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
