apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    provider: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mariadb-root-password: {{ default "" .Values.mariadbRootPassword | b64enc | quote }}
  mariadb-password: {{ default "" .Values.mariadbPassword | b64enc | quote }}
