apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "rabbitmq" | trunc 24 }}
  labels:
    provider: rabbitmq
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: rabbitmq
    port: 15672
    targetPort: rabbitmq
  selector:
    provider: rabbitmq
    release: {{ .Release.Name }}
