apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "rabbitmq" | trunc 24 }}
  labels:
    provider: rabbitmq
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: ampq
    port: {{ .Values.rabbitmqNodeport }}
    targetPort: ampq
  - name: dist
    port: {{ add 20000 .Values.rabbitmqNodeport }}
    targetPort: dist
  - name: stats
    port: {{ .Values.rabbitmqManagerport }}
    targetPort: stats
  selector:
    provider: rabbitmq
    release: {{ .Release.Name }}
