apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "rabbitmq" | trunc 24 }}
  labels:
    provider: rabbitmq
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: rabbitmq
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        provider: rabbitmq
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: {{ printf "%s-%s" .Release.Name "rabbitmq" | trunc 24 }}
        image: bitnami/rabbitmq:{{ .Values.imageTag }}
        env:
        - name: RABBITMQ_USERNAME
          value: {{ default "" .Values.rabbitmqUsername | quote }}
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "rabbitmq" | trunc 24 }}
              key: rabbitmq-password
        - name: RABBITMQ_ERLANGCOOKIE
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "rabbitmq" | trunc 24 }}
              key: rabbitmq-erlangcookie
        - name: RABBITMQ_NODEPORT
          value: {{ default "" .Values.rabbitmqNodeport | quote }}
        - name: RABBITMQ_NODETYPE
          value: {{ default "" .Values.rabbitmqNodetype | quote }}
        - name: RABBITMQ_NODENAME
          value: {{ default "" .Values.rabbitmqNodename | quote }}
        - name: RABBITMQ_CLUSTERNODENAME
          value: {{ default "" .Values.rabbitmqClusternodename | quote }}
        - name: RABBITMQ_VHOST
          value: {{ default "" .Values.rabbitmqVhost | quote }}
        - name: RABBITMQ_MANAGERPORT
          value: {{ default "" .Values.rabbitmqManagerport | quote }}
        ports:
        - name: epmd
          containerPort: 4369
        - name: ampq
          containerPort: {{ .Values.rabbitmqNodeport }}
        - name: dist
          containerPort: {{ add 20000 .Values.rabbitmqNodeport }}
        - name: stats
          containerPort: {{ .Values.rabbitmqManagerport }}
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /bitnami/rabbitmq
      volumes:
      - name: rabbitmq-data
        emptyDir: {}
