name: bitnami-common
version: 0.0.3
appVersion: 0.0.1
description: Chart with custom tempaltes used in Bitnami charts.
keywords:
- helper
- template
- bitnami
- broker
- service
- catalog
maintainers:
- name: bitnami-bot
  email: containers@bitnami.com
engine: gotpl
