apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ printf "%s-%s" .Release.Name "ghost" | trunc 24 }}
  labels:
    app: ghost
    provider: ghost-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: ghost
    provider: ghost-server
    release: {{ .Release.Name }}
    version: {{ .Values.imageTag }}
  template:
    metadata:
      labels:
        app: ghost
        provider: ghost-server
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: ghost
        image: bitnami/ghost:{{ .Values.imageTag }}
        env:
        - name: MARIADB_HOST
          value: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 | quote }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
              key: mariadb-root-password
        - name: GHOST_HOST
          value: {{ default .Values.ghostHostIP .Values.ghostHost | quote }}
        - name: GHOST_PORT
          value: {{ default "" .ghostPort | quote }}
        - name: GHOST_USERNAME
          value: {{ default "" .Values.ghostUser | quote }}
        - name: GHOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "ghost" | trunc 24 }}
              key: ghost-password
        - name: GHOST_EMAIL
          value: {{ default "" .Values.ghostEmail | quote }}
        - name: BLOG_TITLE
          value: {{ default "" .Values.blogTitle | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "ghost" | trunc 24 }}
              key: smtp-password
        - name: SMTP_SERVICE
          value: {{ default "" .Values.smtpService | quote }}
        ports:
        - name: http
          containerPort: 2368
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/ghost
      volumes:
      - name: data
        emptyDir: {}
