#helm:generate helmc tpl -d tpl/values.toml -o manifests/wildfly-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: wildfly
  labels:
    provider: wildfly
    heritage: bitnami
type: Opaque
data:
  wildfly-password: {{ .wildflyPassword | b64enc | quote }}
