#helm:generate helmc tpl -d tpl/values.toml -o manifests/testlink-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: testlink
  labels:
    provider: testlink
    heritage: bitnami
type: Opaque
data:
  testlink-password: "Yml0bmFtaQ=="
  smtp-password: ""
