#helm:generate helmc tpl -d tpl/values.toml -o manifests/ghost-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: ghost
  labels:
    provider: ghost
    heritage: bitnami
type: Opaque
data:
  ghost-password: "Yml0bmFtaTE="
  smtp-password: ""
