apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
    provider: ghost-server
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: ghost
    provider: ghost-server
