#helm:generate helmc tpl -d tpl/values.toml -o manifests/mariadb-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    provider: mariadb
    heritage: bitnami
type: Opaque
data:
  mariadb-root-password: {{ .mariadbRootPassword | b64enc | quote }}
  mariadb-password: {{ .mariadbPassword | b64enc | quote }}
  mariadb-replication-password: {{ .mariadbReplicationPassword | b64enc | quote }}
