image:
  ## Elasticsearch image
  ## ref: https://hub.docker.com/r/bitnami/elasticsearch/tags/
  name: bitnami/elasticsearch
  tag: 5.5.2-r0
  ## Specify a imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

service:
  ## For minikube, set this to NodePort, elsewhere use LoadBalancer
  ##
  type: ClusterIP
  port:
    ## Elasticsearch REST port
    ## ref: https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables
    ##
    http: 9200
    ## Elasticsearch transport port
    ## ref: https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables
    ##
    transport: 9300

cluster:
  ## Elasticsearch cluster name
  ## ref: https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables
  ##
  name: elasticsearch-cluster
  serviceAccountName: default
  plugins: io.fabric8:elasticsearch-cloud-kubernetes:5.5.2
  config:

node:
  master:
    name: master
    replicas: 1
    heapSize: 256m
    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      requests:
        memory: "256Mi"

  data:
    name: data
    replicas: 3
    heapSize: 256m
    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      requests:
        memory: "256Mi"
    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      ## If true, use a Persistent Volume Claim, If false, use emptyDir
      ##
      enabled: true

      ## Persistent Volume Claim annotations
      ##
      annotations: {}

      ## Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"

      ## Persistent Volume Access Mode
      accessModes:
      - ReadWriteOnce

      ## Persistent Volume size
      ##
      size: 8Gi
