apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 24 }}
  labels:
    provider: apache
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: http
    port: 80
  - name: https
    targetPort: https
    port: 443
  selector:
    provider: apache
    release: {{ .Release.Name }}
