apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "redmine" | trunc 24 }}
  labels:
    app: redmine
    provider: redmine-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: redmine
    provider: redmine-server
    release: {{ .Release.Name }}
