apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    provider: redmine
    release: {{ .Release.Name }}
    heritage: bitnami
type: Opaque
data:
  redmine-password: {{ default "" .Values.redminePassword | b64enc | quote }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
