apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name "redmine" | trunc 24 }}
  labels:
    app: redmine
    provider: redmine-server
    release: {{ .Release.Name }}
    heritage: bitnami
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redmine
        provider: redmine-server
        release: {{ .Release.Name }}
        version: {{ .Values.imageTag }}
        heritage: bitnami
    spec:
      containers:
      - name: redmine
        image: bitnami/redmine:{{ .Values.imageTag }}
        env:
        - name: MARIADB_HOST
          value: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 | quote }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "mariadb" | trunc 24 }}
              key: mariadb-root-password
        - name: REDMINE_USERNAME
          value: {{ default "" .Values.redmineUser | quote }}
        - name: REDMINE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "redmine" | trunc 24 }}
              key: redmine-password
        - name: REDMINE_EMAIL
          value: {{ default "" .Values.redmineEmail | quote }}
        - name: REDMINE_LANG
          value: {{ default "" .Values.redmineLanguage | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "redmine" | trunc 24 }}
              key: smtp-password
        - name: SMTP_TLS
          value: {{ default "" .Values.smtpTls | quote }}
        ports:
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/redmine
      volumes:
      - name: data
        emptyDir: {}
