apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: redmine
    provider: redmine-server
    release: {{ .Release.Name }}
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: redmine
    provider: redmine-server
    release: {{ .Release.Name }}
