apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: redmine
    provider: mariadb
    heritage: bitnami
spec:
  ports:
  - port: 3306
  selector:
    app: redmine
    provider: mariadb
