apiVersion: v1
kind: Service
metadata:
  name: redmine
  labels:
    app: redmine
    heritage: bitnami
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: redmine-http
  selector:
    app: redmine
