#helm:generate helmc tpl -d tpl/values.toml -o manifests/redmine-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine
  labels:
    app: redmine
    provider: redmine-server
    heritage: bitnami
spec:
  replicas: 1
  selector:
    app: redmine
    provider: redmine-server
    version: 3.2.3-r0
  template:
    metadata:
      labels:
        app: redmine
        provider: redmine-server
        version: 3.2.3-r0
        heritage: bitnami
    spec:
      containers:
      - name: redmine
        image: bitnami/redmine:3.2.3-r0
        env:
        - name: MARIADB_HOST
          value: "mariadb"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-root-password
        - name: REDMINE_USERNAME
          value: "user"
        - name: REDMINE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redmine
              key: redmine-password
        - name: REDMINE_EMAIL
          value: "user@example.com"
        - name: REDMINE_LANG
          value: "en"
        - name: SMTP_HOST
          value: ""
        - name: SMTP_PORT
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redmine
              key: smtp-password
        - name: SMTP_TLS
          value: ""
        ports:
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/redmine
      volumes:
      - name: data
        emptyDir: {}
