apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    provider: nginx
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: nginx
    version: 1.9.9-0
  template:
    metadata:
      labels:
        provider: nginx
        version: 1.9.9-0
        heritage: bitnami
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.9.9-0
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: htdocs
          mountPath: /app
        - name: conf
          mountPath: /bitnami/nginx/conf
        - name: logs
          mountPath: /bitnami/nginx/logs
      volumes:
      - name: htdocs
        emptyDir: {}
      - name: conf
        emptyDir: {}
      - name: logs
        emptyDir: {}
